version: '3.8'

services:
  payload:
    container_name: shinshin-app
    build:
      context: .
      target: deps
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app:cached
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    stdin_open: true
    tty: true
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped

  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9090"
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    command: postgres -c shared_buffers=128MB -c work_mem=4MB -c maintenance_work_mem=64MB -c effective_cache_size=512MB
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
    name: shinshin-pgdata
  node_modules:
    name: shinshin-node-modules
  minio_storage:
    name: shinshin-minio
