import '../globals.css'
import { cn } from '@/lib/utils'
import { Inter } from 'next/font/google'
import { StagewiseToolbar } from '@stagewise/toolbar-next'
import { ReactPlugin } from '@stagewise-plugins/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shin Shin Group',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, 'relative bg-others-white subpixel-antialiased')}
        suppressHydrationWarning
      >
        <StagewiseToolbar
          config={{
            plugins: [ReactPlugin],
          }}
        />
        {children}
      </body>
    </html>
  )
}
