import '../globals.css'
import { cn } from '@/lib/utils'
import { Inter } from 'next/font/google'
import Menu from '../_components/menu/Menu'
import Footer from '../_components/shared/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shin Shin Group',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'relative bg-others-white subpixel-antialiased')}>
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  )
}
